/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Icon;

/**
 *
 * @author Admin
 */
public class Form_Sach_NCC extends javax.swing.JFrame {

    /**
     * Creates new form Form_Sach_NCC
     */
    public Form_Sach_NCC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PANEL_SACH = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        l_maSach = new javax.swing.JLabel();
        l_tenSach = new javax.swing.JLabel();
        l_TheLoai = new javax.swing.JLabel();
        l_TacGia = new javax.swing.JLabel();
        l_NgaySangTac = new javax.swing.JLabel();
        l_GiaBan = new javax.swing.JLabel();
        l_HinhAnh = new javax.swing.JLabel();
        l_maNCC = new javax.swing.JLabel();
        txt_maSach = new javax.swing.JTextField();
        txt_tenSach = new javax.swing.JTextField();
        txt_TheLoai = new javax.swing.JTextField();
        txt_TacGia = new javax.swing.JTextField();
        txt_ngaySangTac = new javax.swing.JTextField();
        txt_GiaBan = new javax.swing.JTextField();
        txt_hinhAnh = new javax.swing.JTextField();
        txt_maNCC = new javax.swing.JTextField();
        b_Them = new javax.swing.JButton();
        b_Sua = new javax.swing.JButton();
        b_Xoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Sach = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        l_MaNCC = new javax.swing.JLabel();
        l_tenNCC = new javax.swing.JLabel();
        l_DiaChi = new javax.swing.JLabel();
        l_SDT = new javax.swing.JLabel();
        l_soTaiKhoan = new javax.swing.JLabel();
        l_TenTaiKhoan = new javax.swing.JLabel();
        txt_MaNcc = new javax.swing.JTextField();
        txt_TenNCC = new javax.swing.JTextField();
        txt_diaChiNCC = new javax.swing.JTextField();
        txt_SdtNCC = new javax.swing.JTextField();
        txt_STKNcc = new javax.swing.JTextField();
        txt_TenTaiKhoanNCC = new javax.swing.JTextField();
        b_ThemNCC = new javax.swing.JButton();
        b_SuaNCC = new javax.swing.JButton();
        b_XoaNCC = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(153, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        PANEL_SACH.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        l_maSach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_maSach.setForeground(new java.awt.Color(51, 153, 255));
        l_maSach.setText("Mã sách:");

        l_tenSach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_tenSach.setForeground(new java.awt.Color(51, 153, 255));
        l_tenSach.setText("Tên sách:");

        l_TheLoai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_TheLoai.setForeground(new java.awt.Color(51, 153, 255));
        l_TheLoai.setText("Thể loại :");

        l_TacGia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_TacGia.setForeground(new java.awt.Color(51, 153, 255));
        l_TacGia.setText("Tác giả:");

        l_NgaySangTac.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_NgaySangTac.setForeground(new java.awt.Color(51, 153, 255));
        l_NgaySangTac.setText("Ngày sáng tác:");

        l_GiaBan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_GiaBan.setForeground(new java.awt.Color(51, 153, 255));
        l_GiaBan.setText("Giá bán:");

        l_HinhAnh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_HinhAnh.setForeground(new java.awt.Color(51, 153, 255));
        l_HinhAnh.setText("Hình ảnh");

        l_maNCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_maNCC.setForeground(new java.awt.Color(51, 153, 255));
        l_maNCC.setText("Mã NCC:");

        txt_maSach.setText("jTextField1");

        txt_tenSach.setText("jTextField2");

        txt_TheLoai.setText("jTextField3");

        txt_TacGia.setText("jTextField5");

        txt_ngaySangTac.setText("jTextField6");

        txt_GiaBan.setText("jTextField7");

        txt_hinhAnh.setText("jTextField8");

        txt_maNCC.setText("jTextField9");

        b_Them.setBackground(new java.awt.Color(51, 153, 255));
        b_Them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_Them.setForeground(new java.awt.Color(255, 255, 255));
        b_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        b_Them.setText("THÊM");

        b_Sua.setBackground(new java.awt.Color(51, 153, 255));
        b_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_Sua.setForeground(new java.awt.Color(255, 255, 255));
        b_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit.png"))); // NOI18N
        b_Sua.setText("SỬA");

        b_Xoa.setBackground(new java.awt.Color(51, 153, 255));
        b_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        b_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        b_Xoa.setText("XÓA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_tenSach)
                    .addComponent(l_TheLoai)
                    .addComponent(l_TacGia)
                    .addComponent(l_maSach))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txt_maSach, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tenSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_TheLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_TacGia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_GiaBan)
                    .addComponent(l_NgaySangTac)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(l_maNCC)
                        .addComponent(l_HinhAnh)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ngaySangTac, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(b_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(b_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(l_maSach))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l_NgaySangTac)
                                    .addComponent(txt_ngaySangTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_tenSach)
                            .addComponent(txt_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_GiaBan))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(l_TheLoai)
                                .addComponent(txt_hinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(l_HinhAnh))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_TacGia)
                            .addComponent(l_maNCC)
                            .addComponent(txt_maNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_maSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(txt_tenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txt_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bookX2.png"))); // NOI18N
        jLabel1.setText("SÁCH");

        table_Sach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Thể loại", "Tác giả", "Ngày sáng tác", "Giá bán", "Hình ảnh", "Mã NCC"
            }
        ));
        jScrollPane1.setViewportView(table_Sach);

        javax.swing.GroupLayout PANEL_SACHLayout = new javax.swing.GroupLayout(PANEL_SACH);
        PANEL_SACH.setLayout(PANEL_SACHLayout);
        PANEL_SACHLayout.setHorizontalGroup(
            PANEL_SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_SACHLayout.createSequentialGroup()
                .addGroup(PANEL_SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANEL_SACHLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PANEL_SACHLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANEL_SACHLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        PANEL_SACHLayout.setVerticalGroup(
            PANEL_SACHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_SACHLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SÁCH", new javax.swing.ImageIcon(getClass().getResource("/Icon/book_73.png")), PANEL_SACH); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        l_MaNCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_MaNCC.setForeground(new java.awt.Color(51, 153, 255));
        l_MaNCC.setText("Mã NCC:");

        l_tenNCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_tenNCC.setForeground(new java.awt.Color(51, 153, 255));
        l_tenNCC.setText("Tên NCC:");

        l_DiaChi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_DiaChi.setForeground(new java.awt.Color(51, 153, 255));
        l_DiaChi.setText("Địa chỉ:");

        l_SDT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_SDT.setForeground(new java.awt.Color(51, 153, 255));
        l_SDT.setText("Số điện thoại:");

        l_soTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_soTaiKhoan.setForeground(new java.awt.Color(51, 153, 255));
        l_soTaiKhoan.setText("Số tài khoản:");

        l_TenTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_TenTaiKhoan.setForeground(new java.awt.Color(51, 153, 255));
        l_TenTaiKhoan.setText("Tên tài khoản:");

        txt_MaNcc.setText("jTextField1");

        txt_TenNCC.setText("jTextField2");

        txt_diaChiNCC.setText("jTextField3");

        txt_SdtNCC.setText("jTextField5");

        txt_STKNcc.setText("jTextField6");

        txt_TenTaiKhoanNCC.setText("jTextField7");

        b_ThemNCC.setBackground(new java.awt.Color(0, 153, 255));
        b_ThemNCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_ThemNCC.setForeground(new java.awt.Color(255, 255, 255));
        b_ThemNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        b_ThemNCC.setText("THÊM");

        b_SuaNCC.setBackground(new java.awt.Color(0, 153, 255));
        b_SuaNCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_SuaNCC.setForeground(new java.awt.Color(255, 255, 255));
        b_SuaNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit.png"))); // NOI18N
        b_SuaNCC.setText("SỬA");

        b_XoaNCC.setBackground(new java.awt.Color(0, 153, 255));
        b_XoaNCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_XoaNCC.setForeground(new java.awt.Color(255, 255, 255));
        b_XoaNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        b_XoaNCC.setText("XÓA");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã NCC", "Tên NCC", "Địa chỉ", "Số điện thoại", "Số tài khoản", "Tên tài khoản"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_XoaNCC)
                .addGap(223, 223, 223))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(l_MaNCC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_MaNcc, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(l_tenNCC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(b_ThemNCC)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txt_diaChiNCC)
                                                .addComponent(txt_TenNCC))))))
                            .addComponent(l_DiaChi))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l_soTaiKhoan)
                                    .addComponent(l_TenTaiKhoan)
                                    .addComponent(b_SuaNCC))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_STKNcc)
                                    .addComponent(txt_TenTaiKhoanNCC)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(l_SDT)
                                .addGap(34, 34, 34)
                                .addComponent(txt_SdtNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_MaNCC)
                    .addComponent(l_SDT)
                    .addComponent(txt_MaNcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SdtNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_tenNCC)
                    .addComponent(l_soTaiKhoan)
                    .addComponent(txt_TenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_STKNcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_DiaChi)
                    .addComponent(l_TenTaiKhoan)
                    .addComponent(txt_diaChiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenTaiKhoanNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_XoaNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(b_ThemNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_SuaNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/NCC_55.png"))); // NOI18N
        jLabel2.setText("NHÀ CUNG CẤP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("NHÀ CUNG CẤP", new javax.swing.ImageIcon("D:\\ĐẠI HỌC\\NĂM HAIIIIIIIIII\\KÌ 2\\JAVA\\JAVA SWING\\Icon\\NCC.png"), jPanel1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Sach_NCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Sach_NCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Sach_NCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Sach_NCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Sach_NCC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANEL_SACH;
    private javax.swing.JButton b_Sua;
    private javax.swing.JButton b_SuaNCC;
    private javax.swing.JButton b_Them;
    private javax.swing.JButton b_ThemNCC;
    private javax.swing.JButton b_Xoa;
    private javax.swing.JButton b_XoaNCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel l_DiaChi;
    private javax.swing.JLabel l_GiaBan;
    private javax.swing.JLabel l_HinhAnh;
    private javax.swing.JLabel l_MaNCC;
    private javax.swing.JLabel l_NgaySangTac;
    private javax.swing.JLabel l_SDT;
    private javax.swing.JLabel l_TacGia;
    private javax.swing.JLabel l_TenTaiKhoan;
    private javax.swing.JLabel l_TheLoai;
    private javax.swing.JLabel l_maNCC;
    private javax.swing.JLabel l_maSach;
    private javax.swing.JLabel l_soTaiKhoan;
    private javax.swing.JLabel l_tenNCC;
    private javax.swing.JLabel l_tenSach;
    private javax.swing.JTable table_Sach;
    private javax.swing.JTextField txt_GiaBan;
    private javax.swing.JTextField txt_MaNcc;
    private javax.swing.JTextField txt_STKNcc;
    private javax.swing.JTextField txt_SdtNCC;
    private javax.swing.JTextField txt_TacGia;
    private javax.swing.JTextField txt_TenNCC;
    private javax.swing.JTextField txt_TenTaiKhoanNCC;
    private javax.swing.JTextField txt_TheLoai;
    private javax.swing.JTextField txt_diaChiNCC;
    private javax.swing.JTextField txt_hinhAnh;
    private javax.swing.JTextField txt_maNCC;
    private javax.swing.JTextField txt_maSach;
    private javax.swing.JTextField txt_ngaySangTac;
    private javax.swing.JTextField txt_tenSach;
    // End of variables declaration//GEN-END:variables
}
