/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import BUS.Book_BUS;
import DTO.Book;
import DTO.Book_DTO;
import DTO.Check_Error;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author DELL
 */
public class AddBookDialog extends javax.swing.JDialog implements ActionListener {

    /**
     * Creates new form AddBookDialog
     */
    DTO.Check_Error check = new Check_Error();
    static final int BTN_ADD = 0;
    static final int BTN_UPDATE = 1;
    private String iconSting;
    private int location;
    private homeManage homeManage;

    public AddBookDialog(java.awt.Frame parent, boolean modal, homeManage homeManage, int location) {
        super(parent, modal);
        initComponents();
        action();
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        txtAuthor.setVisible(false);
        txtType.setVisible(false);
        txtPrice.setVisible(false);
        txtQuanati.setVisible(false);
        txtDateComposition.setVisible(false);
        txtIDSupplier.setVisible(false);
        jPanel2.setVisible(false);
        btnAdd.setVisible(false);
        btnCancel.setVisible(false);
        btnAdd1.setFocusPainted(false);
        this.location = location;
        iconSting = "";
        this.homeManage = homeManage;
        this.setLocationRelativeTo(null);
        addActionListener();
        System.out.println(location);
        if (location == AddBookDialog.BTN_ADD) {
            this.btnAdd.setText("Thêm");
            this.lbTitle.setText("THÊM SÁCH");
            this.btnAddImage.setText("Thêm Hình Ảnh");

        }
        if (location == AddBookDialog.BTN_UPDATE) {
            this.btnAdd.setText("Cập Nhật");
            this.lbTitle.setText("SỬA SÁCH");
            this.btnAddImage.setText("Cập Nhật Hình Ảnh");
            loadData(this.homeManage.getEditBook());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        btnAddImage = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetails = new javax.swing.JTextArea();
        txtName = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtIDSupplier = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        lbTitle = new javax.swing.JLabel();
        txtQuanati = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lbQuanity = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        txtDateComposition = new javax.swing.JFormattedTextField();
        btnAdd1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hình Ảnh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 153, 255))); // NOI18N

        lbImage.setBackground(new java.awt.Color(102, 102, 102));
        lbImage.setText(" ");
        lbImage.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAddImage.setBackground(new java.awt.Color(0, 153, 255));
        btnAddImage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddImage.setForeground(new java.awt.Color(255, 255, 255));
        btnAddImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add_Image.png"))); // NOI18N
        btnAddImage.setText("Thêm Hình Ảnh");
        btnAddImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddImageActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Tên sách:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Thể loại :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Tác giả:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("Ngày sáng tác :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("Mã nhà cung cấp :");

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHI TIẾT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtDetails.setColumns(20);
        txtDetails.setRows(5);
        txtDetails.setDragEnabled(true);
        jScrollPane1.setViewportView(txtDetails);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );

        txtName.setText(" ");

        txtAuthor.setText(" ");

        txtIDSupplier.setText(" ");
        txtIDSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDSupplierActionPerformed(evt);
            }
        });

        txtType.setText(" ");
        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });

        lbTitle.setBackground(new java.awt.Color(0, 153, 255));
        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/SÁCH.png"))); // NOI18N
        lbTitle.setText("THÊM SÁCH");
        lbTitle.setOpaque(true);

        txtQuanati.setText(" ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setText("Số lượng:");

        txtPrice.setText(" ");
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Giá:");

        btnAdd.setBackground(new java.awt.Color(0, 153, 255));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/THEM_50.png"))); // NOI18N
        btnAdd.setText("THÊM");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 0, 51));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/CANCEL.png"))); // NOI18N
        btnCancel.setText("HỦY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lbQuanity.setText(" ");

        lbPrice.setText(" ");

        btnAdd1.setBackground(new java.awt.Color(0, 153, 255));
        btnAdd1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/THEM_50.png"))); // NOI18N
        btnAdd1.setText("Tìm kiếm");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnAddImage))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIDSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbQuanity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                    .addComponent(lbPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                        .addComponent(txtAuthor, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPrice))
                                    .addGap(6, 6, 6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtQuanati, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                        .addComponent(txtDateComposition)))
                                .addGap(79, 79, 79)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtQuanati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(lbQuanity, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDateComposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtIDSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddImageActionPerformed

    private void txtIDSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDSupplierActionPerformed

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed

        if (txtName.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập tên sách muốn thêm", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            DefaultListModel<String> dlm = new DefaultListModel<String>();

            jList1.setModel(dlm);
        } else {
            Book_BUS a = new Book_BUS();
            ArrayList<Book_DTO> arr = a.getBooksearch(txtName.getText().trim());
            
            if (arr.size() == 0) {
                int answer = JOptionPane.showConfirmDialog(null, "Sách này không có trong kho bạn có muốn thêm mới không?", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (answer == JOptionPane.YES_OPTION) {
                    btnAdd1.setVisible(false);
                    jLabel3.setVisible(true);
                    jLabel4.setVisible(true);
                    jLabel5.setVisible(true);
                    jLabel6.setVisible(true);
                    jLabel8.setVisible(true);
                    jLabel9.setVisible(true);
                    txtAuthor.setVisible(true);
                    txtType.setVisible(true);
                    txtPrice.setVisible(true);
                    txtQuanati.setVisible(true);
                    
                    txtDateComposition.setVisible(true);
                    txtIDSupplier.setVisible(true);
                    jPanel2.setVisible(true);
                    btnAdd.setVisible(true);
                    btnCancel.setVisible(true);
                }
            } else {
                DefaultListModel<String> dlm = new DefaultListModel<String>();
                int i = 0;
                for (Book_DTO x : arr) {
                    dlm.add(i, x.getName()+" - "+x.getID());
                    i++;
                }
                jList1.setModel(dlm);
            }
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    public void action() {
        jList1.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int ans = JOptionPane.showConfirmDialog(null, "Bạn muốn nhập sách này à ?", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (ans == JOptionPane.YES_OPTION) {
                    jList1.setVisible(false);
                    jScrollPane2.setVisible(false);
                    btnAdd1.setVisible(false);
                    jLabel3.setVisible(true);
                    jLabel4.setVisible(true);
                    jLabel5.setVisible(true);
                    jLabel6.setVisible(true);
                    jLabel8.setVisible(true);
                    jLabel9.setVisible(true);
                    txtAuthor.setVisible(true);
                    txtType.setVisible(true);
                    txtPrice.setVisible(true);
                    txtQuanati.setVisible(true);
                    
                    txtDateComposition.setVisible(true);
                    txtIDSupplier.setVisible(true);
                    jPanel2.setVisible(true);
                    btnAdd.setVisible(true);
                    btnCancel.setVisible(true);
                    txtName.setEnabled(false);
                    
                    //>>>>
                    txtAuthor.setEnabled(false);
                    txtType.setEnabled(false);
                    txtPrice.setEnabled(false);
                    txtQuanati.setEnabled(true);
                    
                    txtDateComposition.setEnabled(false);
                    txtIDSupplier.setEnabled(false);
                    //<<<<
                    System.out.println(jList1.getSelectedValue().toString().split(" - ")[1]);
                    txtName.setText(jList1.getSelectedValue().toString().split(" - ")[0]);
                    Book_BUS a = new Book_BUS();
                    ArrayList<Book_DTO> aa = a.findID(jList1.getSelectedValue().toString().split(" - ")[1]);
                    txtAuthor.setText(aa.get(0).getAuthor());
                    txtDateComposition.setText(aa.get(0).getDateComposition());
                    txtPrice.setText(aa.get(0).getPrice());
                    txtType.setText(aa.get(0).getType());
//                    txtQuanati.setText(aa.get(0).getQuanaty());
                    txtIDSupplier.setText(aa.get(0).getID_SUPPLIER());
                    txtDetails.setText(aa.get(0).getDetails());
                    
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddBookDialog dialog = new AddBookDialog(new javax.swing.JFrame(), true, new homeManage(), 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAddImage;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbQuanity;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JFormattedTextField txtDateComposition;
    private javax.swing.JTextArea txtDetails;
    private javax.swing.JTextField txtIDSupplier;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuanati;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables

    private void addActionListener() {
        this.btnAdd.addActionListener(this);
        this.btnAddImage.addActionListener(this);
        this.btnCancel.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        var src = e.getSource();
        if (src.equals(this.btnCancel)) {
            dispose();
        }
        if (src.equals(this.btnAddImage)) {
            chooseImage();
        }
        if (src.equals(this.btnAdd)) {
            int c = 0;
            var name = txtName.getText().trim();
            var type = txtType.getText().trim();
            var quanaty = txtQuanati.getText().trim();
            var author = txtAuthor.getText().trim();
            var price = txtPrice.getText().trim();
            var dateComposition = txtDateComposition.getText();
            var IDSupplier = txtIDSupplier.getText().trim();
            var details = txtDetails.getText().trim();
            var imgSource = this.iconSting;
            if (check.isNumber(quanaty) && Integer.parseInt(quanaty) >= 0) {
                this.lbQuanity.setText(" ");
            } else {
                this.lbQuanity.setText("giá phải là 1 số >= 0");
            }
            if (check.isNumber(price) && Integer.parseInt(quanaty) >= 0) {
                this.lbPrice.setText("");
            } else {
                this.lbPrice.setText("giá phải là 1 số >= 0");
            }

            if (check.isNumber(quanaty) && check.isNumber(price) && Integer.parseInt(price) >= 0 && Integer.parseInt(quanaty) >= 0) {
                if (this.location == AddBookDialog.BTN_ADD) {
                    c = 0;
                    DTO.Book book = new Book(name, type, author, dateComposition,
                            price, this.iconSting, IDSupplier,
                            DAL.WriteDataToSQL.getDay(), quanaty, details);
                    System.out.println(DTO.Book.getCount());
                    DTO.upDateId.updateIDBook(book);
                    c = this.homeManage.AddBookCallBackHomeManage(book);
                    if (c == -1) {
                        dispose();
                        JOptionPane.showMessageDialog(rootPane, "Thêm Sách Thất Bại!");
                    } else {
                        dispose();
                        JOptionPane.showMessageDialog(rootPane, "Thêm Sách Thành Công!");
                    }
                }
                if (this.location == AddBookDialog.BTN_UPDATE) {
                    c = 0;
                    this.homeManage.getEditBook().edit(name, type, quanaty, author, price,
                            dateComposition, IDSupplier, details, this.iconSting);
                    System.out.println(iconSting);
                    c = DAL.EditDataToSQL.editDataBook(this.homeManage.getEditBook());
                    if (c != -1) {
                        this.homeManage.EditBookCallBackManage();
                        dispose();
                        JOptionPane.showMessageDialog(rootPane, "Sửa Sách Thành Công!");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Sửa Sách Thất Bại!");
                    }
                }
            }

        }
    }

    private void chooseImage() {
        var dirPart = "C:\\Users\\DELL\\Desktop\\DoAnBookStory\\DoAnBookStory\\src\\BiaSach";
        File initFile = new File(dirPart);
        JFileChooser fileChooser = new JFileChooser(initFile);
        int actionResult = fileChooser.showOpenDialog(this);
        if (actionResult == JFileChooser.APPROVE_OPTION) {
            var icon = new ImageIcon(fileChooser.getSelectedFile().getAbsolutePath());
            System.out.println(icon);
            lbImage.setIcon(icon);
            this.iconSting = icon + "";
            System.out.println(this.iconSting);
        }
    }

    private void loadData(Book editBook) {
//        System.out.println("haha");
        this.txtName.setText(editBook.getName());
        this.txtType.setText(editBook.getType());
        this.txtAuthor.setText(editBook.getAuthor());
        this.txtPrice.setText(editBook.getPrice());
        this.txtQuanati.setText(editBook.getQuanaty());
//        Date date = new Date("01/01/2003");
//        System.out.println(date);
//        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
//        String  ngaythang= sdf.format(date);
//        this.txtDateComposition.setDate(date);
        this.txtDateComposition.setText(editBook.getDateComposition());
        this.txtIDSupplier.setText(editBook.getID_SUPPLIER());
        this.txtDetails.setText(editBook.getDetails());
        if (editBook.getSourceIMG().contains("/")) {
//                        hinhAnhSach.setIcon(new ImageIcon(getClass().getResource(b.getSourceIMG()) ));
            this.lbImage.setIcon(new ImageIcon(getClass().getResource(editBook.getSourceIMG())));
        } else {
//                         hinhAnhSach.setIcon(new ImageIcon(b.getSourceIMG()));
            this.lbImage.setIcon(new ImageIcon(editBook.getSourceIMG()));
        }
//        this.lbImage.setIcon(new ImageIcon(editBook.getSourceIMG()));
        this.iconSting = editBook.getSourceIMG();

    }

}
