/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DTO.Account;
import DTO.Book;
import DTO.KhachHang;
import DAL.ReadDataFromSQL;
import DAL.WriteDataToSQL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class LoginFRM extends javax.swing.JFrame {

    /**
     * Creates new form LoginFRM
     */
    WriteDataToSQL writeData = new WriteDataToSQL();
    ReadDataFromSQL readData = new ReadDataFromSQL();
    private ArrayList<Account> accounts;
    private final String DATABASE = "PROJECT_BOOKSTOREV5";
    private Account accPre = new Account();
    private ArrayList<DTO.Book> Books = new ArrayList<DTO.Book>();

    public LoginFRM() {

        initComponents();
        loadData();

        accPre = new Account();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    for (DTO.Book b : Books) {
                        
                        //
                        if(b.getSourceIMG().contains("/"))
                        {
                            lbPreview.setIcon(new ImageIcon(getClass().getResource(b.getSourceIMG())));
                        }else lbPreview.setIcon(new ImageIcon(b.getSourceIMG()));
                        //
//                        System.out.println("i");
//                         lbPreview.setIcon(new ImageIcon(getClass().getResource(b.getSourceIMG())));
                       
//                        lbPreview.setIcon(new ImageIcon(b.getSourceIMG()));
                        try {
                            Thread.sleep(3000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(LoginFRM.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }

            }
        }).start();
    }

    public Account getAccPre() {
        return accPre;
    }

    public void setAccPre(Account accPre) {
        this.accPre = accPre;
    }

    public ArrayList<Account> getAccounts() {
        return accounts;
    }

    public void setAccounts(ArrayList<Account> accounts) {
        this.accounts = accounts;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_email_login = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPasswordField_Login = new javax.swing.JPasswordField();
        jButton_Login = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton_SignIn = new javax.swing.JButton();
        lbCheck = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbPreview = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Store");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setToolTipText("");
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐĂNG NHẬP BOOKSTORE");
        jLabel2.setOpaque(true);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/EMAIL.png"))); // NOI18N
        jLabel12.setText("Email:");

        jTextField_email_login.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_email_login.setToolTipText("Email hoặc số điện thoại");
        jTextField_email_login.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField_email_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_email_loginActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Password:");

        jPasswordField_Login.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordField_Login.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPasswordField_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_LoginActionPerformed(evt);
            }
        });

        jButton_Login.setBackground(new java.awt.Color(255, 153, 0));
        jButton_Login.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Login.setText("Đăng Nhập");
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("————————————————————hoặc————————————————————");

        jButton_SignIn.setBackground(new java.awt.Color(102, 255, 102));
        jButton_SignIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_SignIn.setForeground(new java.awt.Color(255, 255, 255));
        jButton_SignIn.setText("TẠO TÀI KHOẢN MỚI");
        jButton_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SignInActionPerformed(evt);
            }
        });

        lbCheck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbCheck.setForeground(new java.awt.Color(255, 51, 0));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lbPreview.setBackground(new java.awt.Color(255, 255, 255));
        lbPreview.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_email_login)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12)
                                .addComponent(jButton_Login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                                .addComponent(jPasswordField_Login))
                            .addComponent(lbCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)
                        .addGap(3, 3, 3)
                        .addComponent(jTextField_email_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordField_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jButton_Login)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_email_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_email_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_email_loginActionPerformed

    private void jPasswordField_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_LoginActionPerformed

    private void jButton_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SignInActionPerformed
        // TODO add your handling code here:
        RegisterCustomerFRM registerfrm = new RegisterCustomerFRM(this, RegisterCustomerFRM.LOGIN);
        registerfrm.setVisible(true);


    }//GEN-LAST:event_jButton_SignInActionPerformed

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
        this.accounts = (ArrayList<Account>) readData.readAccount();
        var txtAccount = this.jTextField_email_login.getText();
        var txtPass = this.jPasswordField_Login.getText();
        Account acc = new Account(txtAccount, txtPass, DAL.WriteDataToSQL.getDay());
        for (Account a : accounts) {
            if (acc.equals(a)) {
                acc = a;
                this.accPre = a;
                break;
            }
        }
        if (accounts.contains(acc)) {
            if (acc.getPosition().equals("Customer")) {
                HomeCustomer homeCustomer = new HomeCustomer(this);
                homeCustomer.setVisible(true);
                dispose();
            } else if (acc.getPosition().equals("Manage")) {
                homeManage homeManage = new homeManage(this);
                homeManage.setVisible(true);
                dispose();

            } else if (acc.getPosition().equals("Staff")) {
                HomeStaff orderBook = new HomeStaff(this);
                orderBook.setVisible(true);
                dispose();
                // hiển thị frame của staff
            } else if (acc.getPosition().equals("stocker")) {
                // hển thị frame của stocker
            }
        } else {
            this.lbCheck.setText("Tài khoản hoặc mật khẩu không đúng!");
        }


    }//GEN-LAST:event_jButton_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFRM().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Login;
    private javax.swing.JButton jButton_SignIn;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField_Login;
    private javax.swing.JTextField jTextField_email_login;
    private javax.swing.JLabel lbCheck;
    private javax.swing.JLabel lbPreview;
    // End of variables declaration//GEN-END:variables

    public void setAccount(Account acc) {
        if (accounts == null) {
            accounts = new ArrayList<Account>();
        }
        accounts.add(acc);

    }

    public void loadData() {
        if (accounts == null) {
            accounts = new ArrayList<Account>();
        }
        accounts = (ArrayList<Account>) readData.readAccount();
        this.Books = (ArrayList<Book>) DAL.ReadDataFromSQL.readBook();
    }

    void addCustomerCallBack(KhachHang KH,int x) {
        this.writeData.insertDataAccount(KH.getAccount());
        int y =this.writeData.insertDataCustomer(KH);
        if(y!=-1)
        {
            this.accounts.add(KH.getAccount());
        }else 
        {
            x=-1;
            DAL.EditDataToSQL.removeDataAccount(KH.getAccount());
        }
    }

    public WriteDataToSQL getWriteData() {
        return writeData;
    }

    public void setWriteData(WriteDataToSQL writeData) {
        this.writeData = writeData;
    }

    public ReadDataFromSQL getReadData() {
        return readData;
    }

    public void setReadData(ReadDataFromSQL readData) {
        this.readData = readData;
    }

    public JButton getjButton_Login() {
        return jButton_Login;
    }

    public void setjButton_Login(JButton jButton_Login) {
        this.jButton_Login = jButton_Login;
    }

    public JButton getjButton_SignIn() {
        return jButton_SignIn;
    }

    public void setjButton_SignIn(JButton jButton_SignIn) {
        this.jButton_SignIn = jButton_SignIn;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPasswordField getjPasswordField_Login() {
        return jPasswordField_Login;
    }

    public void setjPasswordField_Login(JPasswordField jPasswordField_Login) {
        this.jPasswordField_Login = jPasswordField_Login;
    }

    public JTextField getjTextField_email_login() {
        return jTextField_email_login;
    }

    public void setjTextField_email_login(JTextField jTextField_email_login) {
        this.jTextField_email_login = jTextField_email_login;
    }

    public JLabel getLbCheck() {
        return lbCheck;
    }

    public void setLbCheck(JLabel lbCheck) {
        this.lbCheck = lbCheck;
    }

}
