/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import BUS.Book_BUS;
import BUS.HoaDon_BUS;
import DAL.KhachHang_DAO;
import DTO.Book;
import DTO.HoaDon_DTO;
import DTO.KhachHang;
import static GUI.HomeStaff.getDay;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class receiveOderDialog extends javax.swing.JDialog {

    private Book preBook;
    private  KhachHang preCus;
    private float quantity;
    private ArrayList<HoaDon_DTO> HDs;
    private String idHD = "";
    
    
    /**
     * Creates new form receiveOderDialog
     */
    public receiveOderDialog(java.awt.Frame parent, boolean modal,KhachHang preCus ,Book preBook,String quantity) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.preBook =preBook;
        this.preCus =preCus;
        this.quantity =Float.parseFloat(quantity);
        fillData();
        loadDataFromSQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        lbQuantity = new javax.swing.JLabel();
        lbQuantity1 = new javax.swing.JLabel();
        lbQuantity2 = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbQuantity3 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbTotal1 = new javax.swing.JLabel();
        lbTotal2 = new javax.swing.JLabel();
        lbTotal3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        lbName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbName.setText("Sách");

        lbQuantity.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuantity.setText("Số lượng:");

        lbQuantity1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbQuantity1.setText("Số lượng:");

        lbQuantity2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbQuantity2.setText("Giá:");

        lbPrice.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrice.setText("Giá:");

        lbQuantity3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbQuantity3.setText("Tổng tiền:");

        lbTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotal.setText("Giá:");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton1.setText("XÁC NHẬN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbTotal1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTotal1.setText("VNĐ");

        lbTotal2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTotal2.setText("VNĐ");

        lbTotal3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTotal3.setText("VNĐ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbQuantity3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(lbQuantity1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbQuantity2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(lbPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTotal2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(lbTotal3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantity2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuantity3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        float sum = this.quantity*Float.parseFloat(this.preBook.getPrice());
        
       HoaDon_DTO bill= createHD("NOID",this.preCus.getMaKH(),sum);
       float old = Float.parseFloat(this.preBook.getQuanaty());
       float minus = old - quantity;
       this.preBook.setQuanaty(minus+"");
       DAL.EditDataToSQL.editDataBook(preBook);
       writeInSQL(bill);
        JOptionPane.showMessageDialog(rootPane,"Đơn đặt hàng đã được gửi!");
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receiveOderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receiveOderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receiveOderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receiveOderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KhachHang a= new KhachHang();
                Book b = new Book();
                receiveOderDialog dialog = new receiveOderDialog(new javax.swing.JFrame(), true,a,b,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbQuantity;
    private javax.swing.JLabel lbQuantity1;
    private javax.swing.JLabel lbQuantity2;
    private javax.swing.JLabel lbQuantity3;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotal1;
    private javax.swing.JLabel lbTotal2;
    private javax.swing.JLabel lbTotal3;
    // End of variables declaration//GEN-END:variables

    private void fillData() {
        this.lbName.setText(this.preBook.getName());
        this.lbQuantity.setText(quantity+"");
        this.lbPrice.setText(this.preBook.getPrice()+"");
        float sum=Float.parseFloat(this.preBook.getPrice())*(quantity);
        this.lbTotal.setText(sum+"");
        }

    
         public HoaDon_DTO createHD(String idStaff,String idCustomer,float Total){
        HoaDon_DTO tmp = new HoaDon_DTO();
        
        
        tmp.setID_HoaDon("HD"+getIdHdAndUpdate());
        idHD = tmp.getID_HoaDon();
        tmp.setID_Staff(idStaff);
        tmp.setID_Customer(idCustomer);
        tmp.setDateCreate(HomeStaff.getDay());
        tmp.setTotal(Total);
        tmp.setState(true);
       // System.out.println(tmp.toString());
        return tmp;
    }
         
         public  int getIdHdAndUpdate(){
        
       int count = 1000 ;int max = count ;
        for(HoaDon_DTO tmp :HDs ){
            //tmp.getID_CTHD()
            Integer giaTri=Integer.valueOf(tmp.getID_HoaDon().substring(2));//HD1001
            if(max<giaTri)
            {
                max=giaTri;
            }
        }
        max += 1 ;
        return max ;
    }

    private void loadDataFromSQL() {
        HoaDon_BUS hdBus = new HoaDon_BUS();
        HDs = new ArrayList<HoaDon_DTO>();
        HDs = hdBus.getAllHD();
        
    }

    
    private void writeInSQL(HoaDon_DTO hd) {
        
         HoaDon_BUS wr = new HoaDon_BUS();
         System.out.println(wr.addHD(hd));
         
    }

    private void updateQuantity(Book b) {
//        System.out.println(b.getQuanaty());
//         System.out.println(this.quantity);
//          System.out.println(b.getQuanaty());
//        float oldQuantity =Float.parseFloat(b.getQuanaty());
//        System.out.println("old: "+Float.parseFloat(b.getQuanaty()));
//        System.out.println("new: "+quantity);
//        float minus =oldQuantity-this.quantity+1;
//         System.out.println(minus);
//        b.setQuanaty(Float.parseFloat(this.preBook.getQuanaty().trim())-
//                         this.quantity+"");
//       DAL.EditDataToSQL.editDataBook(b);
    }
    
}
