/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import BUS.ChiTietHoaDon_BUS;
import DTO.ChiTietHoaDon_DTO;
import DTO.HoaDon_DTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Admin
 */
public class SoLuongMuaSach extends javax.swing.JDialog {

    /**
     * Creates new form SoLuongMuaSach
     */
    //BUS
    ChiTietHoaDon_BUS cthdBUS = new ChiTietHoaDon_BUS();
    
    private String soLuong ;
    private boolean trangThaiEvent = false;
    private  HomeStaff orderBook ;
    private ArrayList<ChiTietHoaDon_DTO> CTHDs;
    private ArrayList<HoaDon_DTO> HDs;
    
    public SoLuongMuaSach(java.awt.Frame parent, boolean modal,HomeStaff orderBook) {
        super(parent, modal);
        initComponents();
        this.orderBook = orderBook;
        this.setLocationRelativeTo(null);
        //this.getListCTHD();
        System.out.println(trangThaiEvent);
        this.setEnterShortcut(jButton_Contineu);
        this.setAltEShortcut(btn_huy);
        this.setPhimtat();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Contineu = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_SoLuongMua = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jButton_Contineu.setBackground(new java.awt.Color(0, 153, 255));
        jButton_Contineu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Contineu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Contineu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/THEM_50.png"))); // NOI18N
        jButton_Contineu.setText("TIẾP TỤC");
        jButton_Contineu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ContineuActionPerformed(evt);
            }
        });
        jButton_Contineu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_ContineuKeyPressed(evt);
            }
        });

        btn_huy.setBackground(new java.awt.Color(255, 0, 51));
        btn_huy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_huy.setForeground(new java.awt.Color(255, 255, 255));
        btn_huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/CANCEL.png"))); // NOI18N
        btn_huy.setText("HỦY");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("SỐ LƯỢNG:");

        jTextField_SoLuongMua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_SoLuongMua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_SoLuongMuaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_SoLuongMua, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Contineu)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_SoLuongMua, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Contineu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_huyActionPerformed

    private void jButton_ContineuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ContineuActionPerformed
        // TODO add your handling code here:
//        try {
//             if(!jTextField_SoLuongMua.getText().equals("")){
//            soLuong = jTextField_SoLuongMua.getText();
//            if(Integer.parseInt(soLuong)>Integer.parseInt(orderBook.getjTextField_NumberOfBook().getText())){
//                JOptionPane.showMessageDialog(null, "SỐ lượng quá lơn mời bạn nhập lại");
//  
//            }
//            else{
//                trangThaiEvent = true ;
//            System.out.println(trangThaiEvent);
//                this.setVisible(false);
//            }
//
//        }
//        
//        else
//            JOptionPane.showMessageDialog(null, "Mời bạn nhập dữ liệu!");
//  
//        } catch (Exception e) {
//            System.out.println("CÓ LỖI");
//           
//        }
 handleButtonContineuAction();
       
        
    }//GEN-LAST:event_jButton_ContineuActionPerformed

    private void jTextField_SoLuongMuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SoLuongMuaKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_SoLuongMuaKeyTyped

    private void jButton_ContineuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ContineuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ContineuKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed
private void handleButtonContineuAction() {
    try {
        if (!jTextField_SoLuongMua.getText().equals("")) {
            soLuong = jTextField_SoLuongMua.getText();
            if (Integer.parseInt(soLuong) > Integer.parseInt(orderBook.getjTextField_NumberOfBook().getText())) {
                JOptionPane.showMessageDialog(null, "Số lượng quá lớn. Mời bạn nhập lại.");
            } else {
                trangThaiEvent = true;
                System.out.println(trangThaiEvent);
                this.setVisible(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mời bạn nhập dữ liệu!");
        }
    } catch (Exception e) {
        System.out.println("CÓ LỖI");
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoLuongMuaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoLuongMuaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoLuongMuaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoLuongMuaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SoLuongMuaSach dialog = new SoLuongMuaSach(new javax.swing.JFrame(), true, new HomeStaff());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public String getSoLuong() {
        return soLuong;
    }

    public void setSoLuong(String soLuong) {
        this.soLuong = soLuong;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton jButton_Contineu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField_SoLuongMua;
    // End of variables declaration//GEN-END:variables



    //code
    public ArrayList<ChiTietHoaDon_DTO> getCTHDs() {
        return CTHDs;
    }

    public void setCTHDs(ArrayList<ChiTietHoaDon_DTO> CTHDs) {
        this.CTHDs = CTHDs;
    }

   public ArrayList<ChiTietHoaDon_DTO> getListCTHDReturn(){
       CTHDs = new ArrayList<ChiTietHoaDon_DTO>();
       setCTHDs(orderBook.getArrayListCTHDReturn());
       return CTHDs ;
       
   }
    
    public void getListCTHD(){
       CTHDs = new ArrayList<ChiTietHoaDon_DTO>();
       setCTHDs(orderBook.getArrayListCTHDReturn());
       
   }

    public boolean isTrangThaiEvent() {
        return trangThaiEvent;
    }

    public void setTrangThaiEvent(boolean trangThaiEvent) {
        this.trangThaiEvent = trangThaiEvent;
    }
    
     public void setEnterShortcut(JButton button) {
        InputMap inputMap = button.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = button.getActionMap();

        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "EnterPressed");
        actionMap.put("EnterPressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                button.doClick();
            }
        });
    }
     public static void setAltEShortcut(JButton button) {
        InputMap inputMap = button.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = button.getActionMap();

        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_E, KeyEvent.ALT_DOWN_MASK), "CtrlZPressed");
        actionMap.put("CtrlZPressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                button.doClick();
            }
        });
    }
     public void setPhimtat(){
        btn_huy.setMnemonic(KeyEvent.VK_H);
        btn_huy.setToolTipText("Click để thoát!");
        jButton_Contineu.setMnemonic(KeyEvent.VK_T);
        jButton_Contineu.setToolTipText("Click để chọn số lượng!");
 }
    
}
